name: Generate CV PDF After Pages Build

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-pdf:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF from Production Site
        run: |
          wkhtmltopdf -s A4 https://mstephanidhs.github.io/print assets/cv.pdf

      - name: Commit updated PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/cv.pdf
          if git diff --cached --quiet; then
            echo "No changes in PDF"
          else
            git commit -m "Update CV PDF (auto)"
            git push
          fi
